### PR TITLE
Fix/Improve a bunch of things

### PR DESCRIPTION
**Pull request by xNul**
In this PR:

- Immediately stops installation on an error
- Properly activates the environment for each command
- Switches from a depreciated method of GPTQ installation to the recommended method
- Fixes the CUDA version mismatch error (still waiting on confirmation though)
    - #29 
    - #38 
    - https://github.com/oobabooga/text-generation-webui/issues/1440
    - https://github.com/oobabooga/text-generation-webui/issues/1456
- Fixes the "No CUDA runtime is found" error (still waiting on confirmation though)
    - #26 
- Fixes the "Torch not compiled with CUDA enabled" error
    - #27 
    - https://github.com/oobabooga/text-generation-webui/issues/1394 
- Fixes the issue of installing to a separate Windows drive
    - https://github.com/oobabooga/text-generation-webui/issues/1351
- Possibly fixes this error
    - https://github.com/oobabooga/text-generation-webui/issues/1356

### CODE REVIEW

**Comment by jllllll** [comment]
Could you move the webui args to a variable towards the top of the script? I'm thinking that would make it easier for people to add or change arguments.

**Comment by xNul** [comment]
@jllllll oh sure, that's a good idea. Like this?

```python
WEBUI_ARGS="--chat --model-menu"
```

**Comment by jllllll** [comment]
@xNul Yeah, that's good!

**Comment by oobabooga** [comment]
Thanks for the detailed update!

**Pull request merged**
