### PR TITLE
Workaround for Peft not updating their package version on the git repo

### PR DESCRIPTION
**Pull request by jllllll**
This is causing the installer to not update Peft resulting in various issues. The most recent one being:
https://github.com/oobabooga/text-generation-webui/issues/2773

### CODE REVIEW

**Comment by oobabooga** [comment]
Does `pip install git+https://github.com/huggingface/peft@03eb378eb914fbee709ff7c86ba5b1d033b89524` not install that particular commit (the one currently in the requirements.txt)?

**Comment by oobabooga** [comment]
I have made a change to make this more future-proof: uninstalling every git+ package in requirements.txt instead of just peft. Let me know if you agree with this change.

**Comment by jllllll** [comment]
> I have made a change to make this more future-proof: uninstalling every git+ package in requirements.txt instead of just peft. Let me know if you agree with this change.

Yeah, that should be good. I have noticed in the past some git repos not updating package versions, but didn't realize at the time that it was a problem.

**Comment by jllllll** [comment]
@oobabooga I just noticed that the pip uninstall command does not include `-y` resulting in the installer pausing to ask if it should be uninstalled. A minor issue, but it may confuse some people.

Should probably be changed to this:
```python
run_cmd("python -m pip uninstall -y " + package_name, environment=True)
```

**Comment by oobabooga** [comment]
Oops, that's bad. Thanks for letting me know. Fixed here: https://github.com/oobabooga/one-click-installers/commit/a2116e8b2ba661ba0ffc2b917b3c32135c0bfda4

**Pull request merged**
